-- t.PARENT_ITEM_ID에 없는 i.ITEM_ID을 뽑자!!
-- ITEM_TREE 테이블의 PARENT_ITEM_ID 에 있는 ID는 업그레이드 가능
-- 없는 애들은 업그레이드 불가능


SELECT DISTINCT i.ITEM_ID, i.ITEM_NAME, i.RARITY	
FROM ITEM_INFO i
WHERE i.ITEM_ID NOT IN (
    SELECT t.PARENT_ITEM_ID
    FROM ITEM_TREE t
    WHERE t.PARENT_ITEM_ID IS NOT NULL
)
ORDER BY i.ITEM_ID DESC;
