-- 완료된 중고 거래의 총금액이 70만 원 이상인 사람의 회원 ID, 닉네임, 총거래금액을 조회하는 SQL문을 작성.
-- 결과는 총거래금액을 기준으로 오름차순 정렬

SELECT u.USER_ID, u.NICKNAME, SUM(b.PRICE) AS TOTAL_SALES 
FROM USED_GOODS_USER u
JOIN USED_GOODS_BOARD b
    ON u.USER_ID = b.WRITER_ID
WHERE b.STATUS = 'DONE'
GROUP BY b.WRITER_ID
HAVING SUM(b.PRICE) >= 700000
ORDER BY TOTAL_SALES 